backend:
  name: git-gateway
  branch: main
media_folder: "img/uploads"
public_folder: "/img/uploads"
collections:
  - name: "menu"
    label: "Menu"
    files:
      - label: "Menu"
        name: "menu"
        file: "data/menu.json"
        format: "json"
        fields:
          - label: "Plats"
            name: "plats"
            widget: list
          - label: "Accompagnements"
            name: "accompagnements"
            widget: list
          - label: "Toppings"
            name: "toppings"
            widget: list
  - name: "content"
    label: "Contenu de la page"
    files:
      - label: "Contenu principal"
        name: "content"
        file: "data/content.json"
        format: "json"
        fields:
          - label: "Images du concept"
            name: "conceptImages"
            widget: list
            field:
              label: "Image"
              name: ""
              widget: image
          - label: "Titre Menu"
            name: "menuSubheading"
            widget: string
          - label: "Texte CTA"
            name: "ctaText"
            widget: text
